CXX=g++
CXXFLAGS=-std=c++17

s10-alphabetical_precedence: s10-alphabetical_precedence-main.cc s10-alphabetical_precedence.cc s10-alphabetical_precedence.h
	$(CXX) $(CXXFLAGS) -o $@ $^

clean:
	rm s10-alphabetical_precedence
