CXX=g++
CXXFLAGS=-std=c++17

s9-ascii_modifications: s9-ascii_modifications-main.cc s9-ascii_modifications.cc s9-ascii_modifications.h
	$(CXX) $(CXXFLAGS) -o $@ $^

clean:
	rm s9-ascii_modifications

